[package]
name = "uring"
version = "0.1.0"
authors = ["Matt Hunzinger <matthunz2@gmail.com>"]
edition = "2018"

[dependencies]
sys-call = { git = "https://github.com/matthunz/sys-call-rs" }

[dev-dependencies]
tempfile = "3.1.0"
